#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SIMS_BARS.Resource", IsApplication=true)]

namespace SIMS_BARS
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int SlideRight = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int SlideUp = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int alignmentMode = 2130771972;
			
			// aapt resource value: 0x7f010002
			public const int columnCount = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int columnOrderPreserved = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int layout_column = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int layout_columnSpan = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int layout_columnWeight = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int layout_gravity = 2130771981;
			
			// aapt resource value: 0x7f010007
			public const int layout_row = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int layout_rowSpan = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int layout_rowWeight = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int orientation = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int rowCount = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int rowOrderPreserved = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int useDefaultMargins = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int default_gap = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icons8_1_circle_c_48px = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icons8_2_circle_c_48px = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icons8_3_circle_c_48px = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icons8_4_circle_c_48px = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icons8_Alphabetical_Sorting_25px = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icons8_Alphabetical_Sorting_25px_1 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icons8_Corn_72px_1 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icons8_Corn_72px_2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icons8_Document_65px = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icons8_Documents_65px = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icons8_Edit_File_65px = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icons8_Exit_65px = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icons8_Farmer_48px = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icons8_inspection_48px = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icons8_Male_User_48px = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icons8_Open_65px = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icons8_paper_bag_with_seeds_48px = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int icons8_paper_bag_with_seeds_48px_1 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int icons8_Planner_48px = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int icons8_Radio_Tower_65px = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int icons8_report_card_48px = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int icons8_Save_65px = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int icons8_settings_208px = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int icons8_settings_35px = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int icons8_Sorting_Arrows_25px = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int icons8_Sorting_Options_25px = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int icons8_Sync_65px = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int icons8_Upload_to_Cloud_65px = 2130837532;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080012
			public const int AllClientsListView = 2131230738;
			
			// aapt resource value: 0x7f080034
			public const int ChkVerifyAcreage = 2131230772;
			
			// aapt resource value: 0x7f080039
			public const int ChkVerifyIdentificationRemovalOfftype = 2131230777;
			
			// aapt resource value: 0x7f080045
			public const int ChkVerifyMaintanceOfIsolationDistance = 2131230789;
			
			// aapt resource value: 0x7f08002d
			public const int ChkVerifyMaturity = 2131230765;
			
			// aapt resource value: 0x7f080046
			public const int ChkVerifyOff_TypeRemovalProperRouging = 2131230790;
			
			// aapt resource value: 0x7f080038
			public const int ChkVerifyOff_typePlantFound = 2131230776;
			
			// aapt resource value: 0x7f08003f
			public const int ChkVerifyPreviousInspectionIssuesTakenCareOff = 2131230783;
			
			// aapt resource value: 0x7f080036
			public const int ChkVerifyProperRouging = 2131230774;
			
			// aapt resource value: 0x7f080033
			public const int ChkVerifySource = 2131230771;
			
			// aapt resource value: 0x7f080035
			public const int ChkVerifyUniformity = 2131230773;
			
			// aapt resource value: 0x7f080015
			public const int ClientsListViewInspectionType = 2131230741;
			
			// aapt resource value: 0x7f08001c
			public const int ClientsOPtions = 2131230748;
			
			// aapt resource value: 0x7f08001b
			public const int IconImage = 2131230747;
			
			// aapt resource value: 0x7f080016
			public const int IconImageClients = 2131230742;
			
			// aapt resource value: 0x7f08006d
			public const int IconImageSowingReport = 2131230829;
			
			// aapt resource value: 0x7f080017
			public const int IdText = 2131230743;
			
			// aapt resource value: 0x7f08006e
			public const int IdTextSowingReport = 2131230830;
			
			// aapt resource value: 0x7f080029
			public const int ImageView_view = 2131230761;
			
			// aapt resource value: 0x7f08004a
			public const int LinearLayoutDialogSettings = 2131230794;
			
			// aapt resource value: 0x7f080073
			public const int SowingReport_on_Client_ListView = 2131230835;
			
			// aapt resource value: 0x7f08005d
			public const int TextAcreage = 2131230813;
			
			// aapt resource value: 0x7f080065
			public const int TextBankAcknowledgement = 2131230821;
			
			// aapt resource value: 0x7f080066
			public const int TextBankName = 2131230822;
			
			// aapt resource value: 0x7f08005a
			public const int TextCertificationNo = 2131230810;
			
			// aapt resource value: 0x7f08005e
			public const int TextClass = 2131230814;
			
			// aapt resource value: 0x7f080058
			public const int TextClientName = 2131230808;
			
			// aapt resource value: 0x7f080031
			public const int TextClientNameInspection = 2131230769;
			
			// aapt resource value: 0x7f08002b
			public const int TextClientNameInspectionPhaseFour = 2131230763;
			
			// aapt resource value: 0x7f08003d
			public const int TextClientNameInspectionPhaseThree = 2131230781;
			
			// aapt resource value: 0x7f080043
			public const int TextClientNameInspectionPhaseTwo = 2131230787;
			
			// aapt resource value: 0x7f08005b
			public const int TextCoordinates = 2131230811;
			
			// aapt resource value: 0x7f080059
			public const int TextCropName = 2131230809;
			
			// aapt resource value: 0x7f080032
			public const int TextCropNameInspection = 2131230770;
			
			// aapt resource value: 0x7f08002c
			public const int TextCropNameInspectionPhaseFour = 2131230764;
			
			// aapt resource value: 0x7f08003e
			public const int TextCropNameInspectionPhaseThree = 2131230782;
			
			// aapt resource value: 0x7f080044
			public const int TextCropNameInspectionPhaseTwo = 2131230788;
			
			// aapt resource value: 0x7f080064
			public const int TextDateBought = 2131230820;
			
			// aapt resource value: 0x7f080060
			public const int TextDateOfSowing = 2131230816;
			
			// aapt resource value: 0x7f08003a
			public const int TextInspectorRemarks = 2131230778;
			
			// aapt resource value: 0x7f08002e
			public const int TextInspectorRemarksPhaseFour = 2131230766;
			
			// aapt resource value: 0x7f080040
			public const int TextInspectorRemarksPhaseThree = 2131230784;
			
			// aapt resource value: 0x7f080047
			public const int TextInspectorRemarksPhaseTwo = 2131230791;
			
			// aapt resource value: 0x7f080037
			public const int TextIsolationDistance = 2131230775;
			
			// aapt resource value: 0x7f080030
			public const int TextLinkSowingReport = 2131230768;
			
			// aapt resource value: 0x7f08002a
			public const int TextLinkSowingReportPhaseFour = 2131230762;
			
			// aapt resource value: 0x7f08003c
			public const int TextLinkSowingReportPhaseThree = 2131230780;
			
			// aapt resource value: 0x7f080042
			public const int TextLinkSowingReportPhaseTwo = 2131230786;
			
			// aapt resource value: 0x7f080068
			public const int TextMobileAcknowledgement = 2131230824;
			
			// aapt resource value: 0x7f080069
			public const int TextMobileServiceName = 2131230825;
			
			// aapt resource value: 0x7f080063
			public const int TextPurchaseBill = 2131230819;
			
			// aapt resource value: 0x7f08005f
			public const int TextSeedsUsed = 2131230815;
			
			// aapt resource value: 0x7f080061
			public const int TextSource = 2131230817;
			
			// aapt resource value: 0x7f080062
			public const int TextTagNo = 2131230818;
			
			// aapt resource value: 0x7f08006a
			public const int TextTransactionId = 2131230826;
			
			// aapt resource value: 0x7f08005c
			public const int TextVariety = 2131230812;
			
			// aapt resource value: 0x7f080067
			public const int TextViewDepositSlip = 2131230823;
			
			// aapt resource value: 0x7f08006c
			public const int TextViewPurchaseBill = 2131230828;
			
			// aapt resource value: 0x7f08006b
			public const int TextViewTagSource = 2131230827;
			
			// aapt resource value: 0x7f080013
			public const int TxtInspectionType = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int TxtInspectionsFound = 2131230740;
			
			// aapt resource value: 0x7f080002
			public const int alignBounds = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int alignMargins = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int bottom = 2131230724;
			
			// aapt resource value: 0x7f08002f
			public const int btnSavePhaseFourInspection = 2131230767;
			
			// aapt resource value: 0x7f08003b
			public const int btnSavePhaseOneInspection = 2131230779;
			
			// aapt resource value: 0x7f080041
			public const int btnSavePhaseThreeInspection = 2131230785;
			
			// aapt resource value: 0x7f080048
			public const int btnSavePhaseTwoInspection = 2131230792;
			
			// aapt resource value: 0x7f08004d
			public const int btnSaveSettings = 2131230797;
			
			// aapt resource value: 0x7f080057
			public const int btnSettings = 2131230807;
			
			// aapt resource value: 0x7f080055
			public const int btnSignin = 2131230805;
			
			// aapt resource value: 0x7f080028
			public const int btnlogout = 2131230760;
			
			// aapt resource value: 0x7f080026
			public const int btnstart = 2131230758;
			
			// aapt resource value: 0x7f080027
			public const int btnsync = 2131230759;
			
			// aapt resource value: 0x7f080005
			public const int center = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int center_horizontal = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int center_vertical = 2131230727;
			
			// aapt resource value: 0x7f080056
			public const int checkBox1 = 2131230806;
			
			// aapt resource value: 0x7f080070
			public const int classofseedText = 2131230832;
			
			// aapt resource value: 0x7f080008
			public const int clip_horizontal = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int clip_vertical = 2131230729;
			
			// aapt resource value: 0x7f080019
			public const int cropText = 2131230745;
			
			// aapt resource value: 0x7f08006f
			public const int cropTextSowingReport = 2131230831;
			
			// aapt resource value: 0x7f080071
			public const int dateofsowingText = 2131230833;
			
			// aapt resource value: 0x7f08001a
			public const int districtText = 2131230746;
			
			// aapt resource value: 0x7f08004b
			public const int editIpaddress = 2131230795;
			
			// aapt resource value: 0x7f080054
			public const int editPassword = 2131230804;
			
			// aapt resource value: 0x7f08004c
			public const int editPort = 2131230796;
			
			// aapt resource value: 0x7f080052
			public const int editUsername = 2131230802;
			
			// aapt resource value: 0x7f08000a
			public const int end = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int fill = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int fill_horizontal = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int fill_vertical = 2131230733;
			
			// aapt resource value: 0x7f080000
			public const int horizontal = 2131230720;
			
			// aapt resource value: 0x7f080024
			public const int imageView1 = 2131230756;
			
			// aapt resource value: 0x7f080025
			public const int lblusername = 2131230757;
			
			// aapt resource value: 0x7f08000e
			public const int left = 2131230734;
			
			// aapt resource value: 0x7f08004e
			public const int linearLayout = 2131230798;
			
			// aapt resource value: 0x7f080022
			public const int linearlayout = 2131230754;
			
			// aapt resource value: 0x7f080074
			public const int listview = 2131230836;
			
			// aapt resource value: 0x7f08001d
			public const int listviewClientsOptions = 2131230749;
			
			// aapt resource value: 0x7f080049
			public const int listviewInspections = 2131230793;
			
			// aapt resource value: 0x7f080075
			public const int nameText = 2131230837;
			
			// aapt resource value: 0x7f080018
			public const int nameTextClient = 2131230744;
			
			// aapt resource value: 0x7f080072
			public const int nameTextSowingReportOwner = 2131230834;
			
			// aapt resource value: 0x7f08001f
			public const int radioButton1 = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int radioButton2 = 2131230752;
			
			// aapt resource value: 0x7f080021
			public const int radioButton3 = 2131230753;
			
			// aapt resource value: 0x7f08001e
			public const int radioGroup1 = 2131230750;
			
			// aapt resource value: 0x7f080023
			public const int relativeLayout1 = 2131230755;
			
			// aapt resource value: 0x7f08000f
			public const int right = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int start = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int top = 2131230737;
			
			// aapt resource value: 0x7f080050
			public const int txtLogin = 2131230800;
			
			// aapt resource value: 0x7f080053
			public const int txtPassword = 2131230803;
			
			// aapt resource value: 0x7f08004f
			public const int txtTitle = 2131230799;
			
			// aapt resource value: 0x7f080051
			public const int txtUsername = 2131230801;
			
			// aapt resource value: 0x7f080001
			public const int vertical = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Appointments = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AppointmentsListView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Clients = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ClientsInspectedList = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ClientsListView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ClientsListViewSowingInspection = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ClientsOptions = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int DialogViewSortingClients = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Home = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ImageViewer = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Inspection_Phase_Four = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Inspection_Phase_One = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Inspection_Phase_Three = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Inspection_Phase_Two = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int InspectionsListView = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int ScaleImage = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Settings = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int SignIn = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int SowingReport_Page = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int SowingReportDesign = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int SowingReportsList = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int Start = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int StartListView = 2130903062;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int DialogAnimation = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] GridLayout = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 4
			public const int GridLayout_alignmentMode = 4;
			
			// aapt resource value: 2
			public const int GridLayout_columnCount = 2;
			
			// aapt resource value: 6
			public const int GridLayout_columnOrderPreserved = 6;
			
			// aapt resource value: 0
			public const int GridLayout_orientation = 0;
			
			// aapt resource value: 1
			public const int GridLayout_rowCount = 1;
			
			// aapt resource value: 5
			public const int GridLayout_rowOrderPreserved = 5;
			
			// aapt resource value: 3
			public const int GridLayout_useDefaultMargins = 3;
			
			public static int[] GridLayout_Layout = new int[] {
					16842996,
					16842997,
					16842998,
					16842999,
					16843000,
					16843001,
					16843002,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 1
			public const int GridLayout_Layout_android_layout_height = 1;
			
			// aapt resource value: 2
			public const int GridLayout_Layout_android_layout_margin = 2;
			
			// aapt resource value: 6
			public const int GridLayout_Layout_android_layout_marginBottom = 6;
			
			// aapt resource value: 3
			public const int GridLayout_Layout_android_layout_marginLeft = 3;
			
			// aapt resource value: 5
			public const int GridLayout_Layout_android_layout_marginRight = 5;
			
			// aapt resource value: 4
			public const int GridLayout_Layout_android_layout_marginTop = 4;
			
			// aapt resource value: 0
			public const int GridLayout_Layout_android_layout_width = 0;
			
			// aapt resource value: 10
			public const int GridLayout_Layout_layout_column = 10;
			
			// aapt resource value: 11
			public const int GridLayout_Layout_layout_columnSpan = 11;
			
			// aapt resource value: 12
			public const int GridLayout_Layout_layout_columnWeight = 12;
			
			// aapt resource value: 13
			public const int GridLayout_Layout_layout_gravity = 13;
			
			// aapt resource value: 7
			public const int GridLayout_Layout_layout_row = 7;
			
			// aapt resource value: 8
			public const int GridLayout_Layout_layout_rowSpan = 8;
			
			// aapt resource value: 9
			public const int GridLayout_Layout_layout_rowWeight = 9;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
